---
title: "Mutual Funds Dashboard v1.0"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bootswatch: minty
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(shinyjs)

# Core
library(tidyverse)
library(tidyquant)
library(data.table)
library(tidytable)
library(scales)

# Interactive Visualizations
library(plotly)
```

```{r}
# Load data
data <- fread("data_tidied/full_data.csv")
```

Column {.sidebar}
---------------------------------------------------------------

```{r}
useShinyjs(rmd = TRUE)

pickerInput(
  inputId = "picker_fund",
  label   = h4("Funds:"),
  choices = toupper(unique(data$symbol)),
  selected = c("E1VFVN30", "DCDS"),
  multiple = TRUE,
  options = list(
    `actions-box` = TRUE,
    size = 10,
    `selected-text-format` = "Quy"
  )
)

# Apply Button:
actionButton(inputId = "apply", label = "Apply", icon = icon("play"))

# Reset Button:
actionButton(inputId = "reset", label = "Reset", icon = icon("sync"))

observeEvent(eventExpr = input$reset, handlerExpr = {
  
  updatePickerInput(
    session  = session,
    inputId  = "picker_fund",
    selected = c("E1VFVN30", "DCDS")
  )
  
  # Delay sau khi bam nut reset
  shinyjs::delay(ms = 80, expr = {
    shinyjs::click(id = "apply")
  })
  
  
})
```

```{r}
# After click on Apply button:

data_tbl <- eventReactive(
  
  eventExpr = input$apply,

  valueExpr = {
    
    # Filter data dua theo cac input
    data_filtered <- data %>%
      filter.(symbol %in% tolower(input$picker_fund)) %>%
      pivot_wider.(names_from = symbol,
                  values_from = returns,
                  values_fill = NA_integer_) %>%
      drop_na.()
    
    
    columns <- tolower(input$picker_fund)
    
    data_filtered[1, columns] <- 0  # gia tri dau tien = 0. with = FALSE (?)
    
    return(data_filtered)
  },

  ignoreNULL = FALSE

)
```

Row
---------------------------------------------------------------

### Cumulative Returns Plot:

```{r}
# Chuan bi du lieu
cumulative_returns_tbl <- reactive({

  data_tbl() %>%
    pivot_longer.(names_to  = "symbol",
                  values_to = "returns", -date) %>%
    mutate.(growth = cumprod(1 + returns), .by = symbol) %>% 
    mutate(label_txt = str_glue("Date: {date}
                                Quy: {toupper(symbol)}
                                Loi nhuan tich luy: {scales::percent(growth - 1, accuracy = 0.1)}"))

})

# Add output
output$plotly_cum_returns <- renderPlotly({

  p1 <- cumulative_returns_tbl() %>%
    
    ggplot(aes(x     = date,
               y     = growth,
               color = symbol)) + theme_tq() +

    geom_line(size = 0.7) +
    geom_point(aes(text = label_txt), size = 1) +
    
    expand_limits(y = 0.5) +
    scale_x_date(breaks = scales::pretty_breaks(n = 10)) +
    
    geom_hline(yintercept = 1, 
               linetype   = "dashed", 
               color      = "#7A7574") +
    
    labs(x = "",
         y = "")

  ggplotly(p1, tooltip = "text")

})

# Plot
plotlyOutput(outputId = "plotly_cum_returns")
```

Row
---------------------------------------------------------------

### Rolling returns plot:

```{r}
# Periods:
radioGroupButtons(
  inputId   = "time_period",
  label     = "Period (Thang)",
  choices   = c(6, 
              12,
              24,
              36,
              48),
  selected  = 12,
  status    = "primary",
  justified = TRUE,
  checkIcon = list(
    yes = icon("ok", lib = "glyphicon"))
)
```

```{r}
# Chuan bi du lieu
rolling_returns_tbl <- reactive({
  
  time_period <- as.integer(input$time_period)
  
  data_tbl() %>% 
    pivot_longer.(names_to  = "symbol",
                  values_to = "returns", -date) %>%
    group_by(symbol) %>% 
    mutate(roll_annr = rollapply(returns,
                                 FUN   = function(x) prod(1+x) - 1,
                                 width = time_period,
                                 align = "right",
                                 fill  = NA)) %>%
    mutate(date_2 = lag(date, n = time_period)) %>% 
    ungroup() %>% 
    mutate(label_txt = str_glue("Ngay mua: {date_2}
                                Gia tri tai: {date}
                                Quy: {toupper(symbol)}
                                Return: {scales::percent(roll_annr, accuracy = 0.1)}"))
})

# Add ouput
output$plotly_rolling_returns <- renderPlotly({
  
  p2 <- rolling_returns_tbl() %>% 
    ggplot(aes(x     = date,
               y     = roll_annr,
               color = symbol)) + theme_tq() + 
    
    geom_line(size = 0.7) + 
    geom_point(aes(text = label_txt), size = 1) +
    
    geom_hline(yintercept = 0, 
               linetype   = "dashed", 
               color      = "#7A7574") +
    
    scale_y_continuous(labels = scales::percent_format()) +
    scale_x_date(breaks = scales::pretty_breaks(n = 10)) +
    
    labs(x = "",
         y = "")
  
  ggplotly(p2, tooltip = "text") %>% 
    layout(margin = list(b = 150)) 
  
})

# Plot
plotlyOutput(outputId = "plotly_rolling_returns")
```

